run-basic:
	cd compile && rustc ../basic.rs 
	./compile/basic

run-debug:
	cd compile && rustc ../debug.rs
	./compile/debug

run-primitives:
	cd compile && rustc ../primitives.rs
	./compile/primitives

run-custom-types:
	cd compile && rustc ../custom_types.rs
	./compile/custom_types

run-variable-binding:
	cd compile && rustc ../variable_bindings.rs
	./compile/variable_bindings

run-type-example:
	cd compile && rustc ../type_example.rs
	./compile/type_example

run-conversion:
	cd compile && rustc ../conversion.rs
	./compile/conversion

run-control-flow:
	cd compile && rustc ../control_flow.rs
	./compile/control_flow

run-func-example:
	cd compile && rustc ../func_example.rs
	./compile/func_example

run-module-example:
	cd compile && rustc ../module_example.rs
	./compile/module_example

